(defpackage #:arele
  (:use #:cl
	#:clog
	#:clog-gui
	#:mito
	)
  (:export start-app))

(in-package :arele)

(deftable investor ()
  ((name :col-type (:varchar 128))
   (percentage :col-type :smallint))
  (:table-name "investors")
  )

(deftable item ()
  ((description :col-type (:varchar 128))
   )
  (:table-name "inventory")
  )

(deftable purchase ()
  ((investor-id :references investor)
   (item-id :references item)
   (date :col-type :datetime)
   (quantity :col-type :integer)
   (on-hand :col-type :integer)
   (price :col-type :integer)
   )
  (:table-name "purchases")
  )

(deftable listing ()
  ((purchase-id :references purchase)
   (date :col-type :datetime)
   (quantity :col-type :integer)
   (price :col-type :integer)
   )
  (:table-name "listings")
  )

(deftable sale ()
  ((listing-id :references listing)
   (date :col-type :datetime)
   (quantity :col-type :integer)
   (price :col-type :integer)
   (fees :col-type :integer)
   (shipping :col-type :integer)
   (customer :col-type (:varchar 128))
   )
  (:table-name "sales")
  )

(deftable remittance ()
  ((investor-id :references investor)
   (date :col-type :datetime)
   (amount :col-type :integer)
   )
  (table-name "remittances")
  )

(defun to-dollar (value)
  (let ((result (ppcre:scan-to-strings "(\\d+)(.(\\d{2}))?" value))
	)
    (+ (* 100 (parse-integer (or (first result) "0"))) (parse-integer (or (third result) "0")))
    )
  )

(defun display-dollar (value)
  (format nil "~$" value)
  )

(defun add-investor (&key name percentage)
  (create-dao 'investor :name name :percentage percentage)
  )

(defun add-inventory-item (&key description &allow-other-keys)
  (create-dao 'item :description description)
  )

(defun add-purchase (&key item date quantity price investor &allow-other-keys)
  (create-dao 'purchase :item-id item :date date :quantity quantity :on-hand quantity :price price :investor-id investor)
  )

(defun add-listing (&key purchase date quantity price &allow-other-keys)
  (create-dao 'listing :purchase-id purchase :date date :quantity quantity :price price)
  (execute-sql "update purchases set on_hand = on_hand - ? where id = ?" (list quantity purchase))
  )

(defun on-investor-list (obj)
  (let* ((app (connection-data-item obj "app-data"))
         (win (create-gui-window obj :title "Investors"))
         (panel (create-div (window-content win)))
	 (slots '(:id :name :percentage))
	 )
    (declare (ignorable app))
    (with-clog-create panel
	(table (:bind table)
	       (table-head (:bind th)
			      )
	       (table-body (:bind tb)
			   )
	       )
      (setf (attribute table :border) 1)
      (mapc (lambda (slot)
	      (create-table-column th :content (format nil "~:(~a~)" slot))
	      )
	    slots)
      (mapc (lambda (investor)
	      (with-clog-create tb
		  (table-row (:bind tr)
			     )
		(mapc (lambda (slot)
			(create-table-column tr :content (getf investor slot))
			)
		      slots)
		)
	      )
	    (retrieve-by-sql "select id, name, percentage from investors")
	    )
      )
    )
  )

(defun on-add-investor (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Add Investor" :width 400))
	 (panel (create-div (window-content win)))
	 )
    (declare (ignore app))
    (with-clog-create panel
	(form (:bind f1)
	      (fieldset (:bind fs1)
			(table ()
			       (table-body ()
					   (table-row ()
						      (table-column () (label (:content "Name")))
						      (table-column () (form-element (:bind name :text)))
						      )
					   (table-row ()
						      (table-column () (label (:content "Percentage 0-100")))
						      (table-column () (select (:bind percentage)))
						      )
					   (table-row ()
						      (table-column () (form-element (:submit :value "Submit")))
						      (table-column () (form-element (:reset :value "Reset")))
						      )
					   )
			       )
			)
	      )
      (add-select-option percentage 0 0)
      (add-select-option percentage 30 30 :selected t)
      (add-select-option percentage 100 100)
      (setf (attribute name :required) t
	    (attribute percentage :required) t
	    )
      (set-on-submit f1 (lambda (obj)
			  (declare (ignorable obj))
			  (add-investor :name (value name) :percentage (parse-integer (value percentage)))
			  (setf (attribute f1 :hidden) t)
			  )
		     )
      )
    )
  )

(defun on-inventory-list (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Inventory"))
	 (inventory (create-div (window-content win)))
	 (slots '(:id :description))
	 )
    (declare (ignorable app inventory))
    (with-clog-create inventory
	(table (:bind table)
	       (table-head (:bind th)
			      )
	       (table-body (:bind tb)
			   )
	       )
      (setf (attribute table :border) 1)
      (mapc (lambda (slot)
	      (create-table-column th :content (format nil "~:(~a~)" slot))
	      )
	    slots)
      (mapc (lambda (item)
	      (with-clog-create tb
		  (table-row (:bind tr)
			     )
		(mapc (lambda (slot)
			(create-table-column tr :content (getf item slot))
			)
		      slots)
		)
	      )
	    (retrieve-by-sql "select id, description from inventory")
	    )
      )
    )
  )

(defun on-add-item (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Add Item"))
	 (panel (create-div (window-content win)))
	 )
    (declare (ignore app))
    (with-clog-create panel
	(form (:bind f1)
	      (fieldset (:bind fs1)
			(table ()
			       (table-body ()
					   (table-row ()
						      (table-column () (label (:content "Description")))
						      (table-column () (form-element (:bind description :text)))
						      )
					   (table-row ()
						      (table-column () (form-element (:submit :value "Ok")))
						      (table-column () (form-element (:reset :value "Clear")))
						      )
					   )
			       )
			)
	      )
      (setf (attribute description :requiredp) t)
      (set-on-submit f1 (lambda (obj)
			  (declare (ignore obj))
			  (add-inventory-item :description (value description))
			  (setf (attribute f1 :hidden) t)
			  )
		     )
      )
    )
  )

(defun on-purchases-list (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Purchases" :width 1200))
	 (purchases (create-div (window-content win)))
	 (slots '(:id :investor :item :date :price :quantity :on-hand))
	 )
    (declare (ignorable app purchases))
    (with-clog-create purchases
	(table (:bind table)
	       (table-head (:bind th)
			      )
	       (table-body (:bind tb)
			   )
	       )
      (setf (attribute table :border) 1)
      (mapc (lambda (slot)
	      (create-table-column th :content (format nil "~:(~a~)" slot))
	      )
	    slots)
      (mapc (lambda (purchase)
	      (with-clog-create tb
		  (table-row (:bind tr)
			     )
		(mapc (lambda (slot)
			(create-table-column tr :content (getf purchase slot))
			)
		      slots)
		)
	      )
	    (retrieve-by-sql "select p.id, p.date, p.quantity, p.on_hand, p.price, iv.name as investor, it.description as item from purchases p inner join investors iv on p.investor_id == iv.id inner join inventory it on p.item_id = it.id")
	    )
      )
    )
  )

(defun on-add-purchase (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Add Purchase" :width 1200))
	 (panel (create-div (window-content win)))
	 )
    (declare (ignorable app))
    (with-clog-create panel
	(div ()
	     (form (:bind f1)
		   (fieldset (:bind fs1)
			     (select (:bind item :label (create-label fs1 :content "Select item")))
			     (form-element (:bind date :date :label (create-label fs1 :content "Date")))
			     (form-element (:bind price :text :label (create-label fs1 :content "Price")))
			     (form-element (:bind quantity :number :label (create-label fs1 :content "Quantity")))
			     (select (:bind investor :label (create-label fs1 :content "Select investor")))
			     (br ())
			     (form-element (:submit :value "Ok"))
			     (form-element (:reset :value "Clear"))
			     )
		   )
	     )
      (mapcar (lambda (i)
		(add-select-option item (object-id i) (item-description i)))
	      (retrieve-dao 'item)
	      )
      (mapcar (lambda (i)
		(add-select-option investor (object-id i) (investor-name i)))
	      (retrieve-dao 'investor)
	      )
      (setf (attribute price :pattern) "\\d+([.]\\d\\d)?"
	    (attribute date :required) t
	    (attribute price :required) t
	    (attribute quantity :required) t
	    )
      
      (set-on-submit f1
		     (lambda (obj)
		       (declare (ignore obj))
		       (add-purchase :item (value item) :date (value date) :quantity (value quantity)
				     :price (value price) :investor (value investor))
		       (setf (attribute f1 :hidden) t)
		       )
		     )
      )
    )
  )

(defun on-listings-list (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Listings" :width 1200))
	 (listings (create-div (window-content win)))
	 (slots '(:id :item :date :price :quantity))
	 )
    (declare (ignorable app))
    (with-clog-create listings
	(table (:bind table)
	       (table-head (:bind th)
			      )
	       (table-body (:bind tb)
			   )
	       )
      (setf (attribute table :border) 1)
      (mapc (lambda (slot)
	      (create-table-column th :content (format nil "~:(~a~)" slot))
	      )
	    slots)
      (mapc (lambda (purchase)
	      (with-clog-create tb
		  (table-row (:bind tr)
			     )
		(mapc (lambda (slot)
			(create-table-column tr :content (getf purchase slot))
			)
		      slots)
		)
	      )
	    (retrieve-by-sql "select l.id, l.date, l.quantity, l.price, it.description as item from listings l inner join purchases p on l.purchase_id = p.id inner join inventory it on p.item_id = it.id")
	    )
      )
    )
  )
(defun on-add-listing (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Add Listing" :width 1200))
	 (panel (create-div (window-content win)))
	 (max)
	 )
    (declare (ignorable app))
    (with-clog-create panel
	(div ()
	     (form (:bind f1)
		   (fieldset (:bind fs1)
			     (select (:bind item :label (create-label fs1 :content "Select item")))
			     (form-element (:bind date :date :label (create-label fs1 :content "Date")))
			     (form-element (:bind price :text :label (create-label fs1 :content "Price")))
			     (form-element (:bind quantity :number :label (create-label fs1 :content "Quantity")))
			     (br ())
			     (form-element (:submit :value "Ok"))
			     (form-element (:reset :value "Clear"))
			     )
		   )
	     )
      (mapcar (lambda (i)
		(add-select-option item (object-id i) (item-description i)))
	      (retrieve-dao 'item)
	      )
      (set-on-select item (lambda (obj)
			    (declare (ignore obj))
			    (setf max (or (getf (first (retrieve-by-sql "select max(on_hand) as on_hand from purchases where item_id = ?" :binds (list (value item)))) :on-hand) 0))
			    (create-div panel :content (format nil "~a" max))
			    )
		     )
      (set-on-submit f1
		     (lambda (obj)
		        (declare (ignore obj))
			(let ((purchases (retrieve-by-sql "select p.id, on_hand, date from purchases p inner join inventory i on p.item_id == i.id where on_hand > ? and i.id == ? order by date"
							       :binds (list (value quantity) (value item))))
			     )
			  (if (null purchases)
			      (alert win (format nil "Cannot list: quantity too large."))
			      )
			  (add-listing :purchase (getf (first purchases) :id) :date (value date)
				       :quantity (value quantity) :price (value price)
				       )
			  )
			)
		     )
      )
    )
  )

(defun on-sales-list (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "List Sales" :width 1200))
	 (panel (create-div (window-content win)))
	 (slots '(id date quantity price fees shipping customer investor item))
	 )
    (declare (ignorable app))
    (with-clog-create panel
	(table (:bind table)
	       (table-head (:bind th)
			      )
	       (table-body (:bind tb)
			   )
	       )
      (setf (attribute table :border) 1)
      (mapc (lambda (slot)
	      (create-table-column th :content (format nil "~:(~a~)" slot))
	      )
	    slots)
      (mapc (lambda (purchase)
	      (with-clog-create tb
		  (table-row (:bind tr)
			     )
		(mapc (lambda (slot)
			(create-table-column tr :content (getf purchase slot))
			)
		      slots)
		)
	      )
	    (retrieve-by-sql "select s.id, s.date, s.quantity, s.price, s.fees, s.shipping, s.customer, iv.name as investor, it.description as item from sales s inner join listings l on s.listing_id = l.id inner join purchases p on l.purchase_id = p.id inner join investors iv on p.investor_id == iv.id inner join inventory it on p.item_id = it.id")
	    )
      )
    )
  )

(defun on-add-sale (obj)
  (let* ((app (connection-data-item obj "app-data"))
	 (win (create-gui-window obj :title "Add Sale" :width 1200))
	 (panel (create-div (window-content win)))
	 )
    (declare (ignorable app))
    (with-clog-create panel
	(form (:bind f1)
	      (select (:bind listing :label (create-label f1 :content "Select listing")))
	      (br ())
	      (form-element (:submit :value "Ok"))
	      (form-element (:reset :value "Reset"))
	      )
      (mapc (lambda (l)
	      (add-select-option listing (getf l :id) (getf l :value))
	      )
	    (retrieve-by-sql "select l.id, (l.date || ' ' || i.description || ' ' || l.quantity) as value from listings l inner join purchases p on l.purchase_id = p.id inner join inventory i on p.item_id = i.id")
	    )
      (set-on-submit f1 (lambda (obj)
			  (declare (ignore obj))
			  )
		     )
      )
    )
  )

(defun on-help-about (obj)
  (let* ((about (create-gui-window obj
                                   :title   "About"
                                   :content "<div class='w3-black'>
                                         <center><img src='/img/clogwicon.png'></center>
                                         <center>arele</center>
                                         <center>arele</center></div>
                                         <div><p><center>A New App</center>
                                         <center>(c) 2023 - Fila Kolodny</center></p></div>"
                                   :hidden  t
                                   :width   200
                                   :height  200)))
    (window-center about)
    (setf (visiblep about) t)
    (set-on-window-can-size about (lambda (obj)
                                    (declare (ignore obj))()))))

(defclass app-data ()
  ((data
    :accessor data)))

(defun on-new-window (body)
  (let ((app (make-instance 'app-data)))
    (setf (connection-data-item body "app-data") app)
    (setf (title (html-document body)) "EBay Store Software")
    (clog-gui-initialize body)
    (add-class body "w3-teal")
    (connect-toplevel :sqlite3 :database-name "arele.db")
    (with-clog-create body
	(gui-menu-bar (:bind menu-bar)
		  (gui-menu-drop-down (:content "Investors")
				      (gui-menu-item (:content "Investor List" :on-click 'on-investor-list))
				      (gui-menu-item (:content "Add Investor" :on-click 'on-add-investor))
				      )
		  (gui-menu-drop-down (:content "Inventory")
				      (gui-menu-item (:content "Items" :on-click 'on-inventory-list))
				      (gui-menu-item (:content "Add Item" :on-click 'on-add-item))
				      )
		  (gui-menu-drop-down (:content "Purchases")
				      (gui-menu-item (:content "Purchases List" :on-click 'on-purchases-list))
				      (gui-menu-item (:content "Add Purchase" :on-click 'on-add-purchase))
				      )
		  (gui-menu-drop-down (:content "Listings")
				      (gui-menu-item (:content "Listings List" :on-click 'on-listings-list))
				      (gui-menu-item (:content "Add Listing" :on-click 'on-add-listing))
				      )
		  (gui-menu-drop-down (:content "Sales")
				      (gui-menu-item (:content "Sales List" :on-click 'on-sales-list))
				      (gui-menu-item (:content "Add Sale" :on-click 'on-add-sale))
				      )
		  (gui-menu-drop-down (:content "Help")
				      (gui-menu-item (:content "About" :on-click 'on-help-about))
				      )
		  )
      (create-gui-menu-full-screen menu-bar)
      )
    )
  )

(defun start-app ()
  (initialize 'on-new-window
   :static-root (merge-pathnames "./www/"
                  (asdf:system-source-directory :arele)))
  (open-browser))
